pipeline:
  check:
    image: node9
    commands:
      - ping -c 3 http://ci.resolve.sh

  trigger:
    image: plugins/downstream
    server: http://ci.resolve.sh
    fork: true
    wait: true

    repositories:
      - DevExpress/okrserver
      - DevExpress/orgstruct

    secrets: [ downstream_token ]