pipeline:
  publish:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - /scripts/version nightly ${DRONE_COMMIT} > .nightly-version
      - /scripts/npm_patch_rc
      - /scripts/npm_publish $(cat .nightly-version)
    secrets: [ npm_repository, npm_token ]

  trigger:
    image: plugins/downstream
    server: http://ci.resolve.sh
    fork: true
    wait: true
    repositories:
      - max-vasin/drone-playground-sub1@master

    secrets: [ downstream_token ]
    params:
      - nightly_version=VERSION

#  finish:
#    image: node:9
#    commands:
#      - echo 'Two green builds'