pipeline:
  check:
    image: node:9
    commands:
      - ping -c 3 ci.resolve.sh

  trigger:
    image: plugins/downstream
    server: http://ci.resolve.sh
    fork: true
    wait: true

    repositories:
      - max-vasin/drone-playground-sub1
      - max-vasin/drone-playground-sub2

    secrets: [ downstream_token ]

  finish:
    image: node:9
    commands:
      - echo 'Two green builds'