pipeline:
  publish:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - export REGISTRY_VERSION=$(/scripts/package_json nightly ${DRONE_COMMIT})
      - echo REGISTRY_VERSION=$NIGHTLY_VERSION >> .entry
      - echo REGISTRY_PACKAGE=$(/scripts/package_json name) >> .entry
      - echo REGISTRY_DOWNSTREAM=true >> .entry
      - /scripts/npm_patch_rc
      - /scripts/npm_publish $REGISTRY_VERSION
    secrets: [ npm_repository, npm_token ]

  downstream_registry:
    image: maxvasin/drone-downstream-registry
    pull: true
    registry_path: /data/registry
    action: package-build
    params: .entry
    volumes:
      - /srv/ecs/downstream-registry:/data/registry
    repositories:
      - maxvasin/drone-playground-sub1
      - maxvasin/drone-playground-sub2

#  publish:
#    image: maxvasin/resolve-docker
#    pull: true
#    commands:
#      - export NIGHTLY_VERSION=$(/scripts/package_json nightly ${DRONE_COMMIT})
#      - echo NIGHTLY_VERSION=$NIGHTLY_VERSION >> .nightly
#      - echo NIGHTLY_PACKAGE=$(/scripts/package_json name) >> .nightly
#      - /scripts/npm_patch_rc
#      - /scripts/npm_publish $NIGHTLY_VERSION
#    secrets: [ npm_repository, npm_token ]
#
#  trigger:
#    image: plugins/downstream
#    server: http://ci.resolve.sh
#    fork: true
#    wait: true
#    repositories:
#      - max-vasin/drone-playground-sub1@master
#
#    secrets: [ downstream_token ]
#    params:
#      - .nightly
