pipeline:
  publish:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - /scripts/npm_patch_rc.sh
      - /scripts/npm_publish.sh
    secrets: [ npm_repository, npm_token ]

#  trigger:
#    image: plugins/downstream
#    server: http://ci.resolve.sh
#    fork: true
#    wait: true

#    repositories:
#      - max-vasin/drone-playground-sub1@master
#      - max-vasin/drone-playground-sub2@master

#    secrets: [ downstream_token ]

#  finish:
#    image: node:9
#    commands:
#      - echo 'Two green builds'